//! Autogenerated weights for pallet_summary
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-04-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-1-153`, CPU: `AMD EPYC 7R32`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./avn-parachain-collator
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// frame-weight-template.hbs
// --pallet
// pallet_summary
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// summary_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_summary.
pub trait WeightInfo {
	fn set_periods() -> Weight;
	fn record_summary_calculation(v: u32, r: u32, ) -> Weight;
	fn approve_root_with_end_voting(v: u32, o: u32, ) -> Weight;
	fn approve_root_without_end_voting(v: u32, ) -> Weight;
	fn reject_root_with_end_voting(v: u32, o: u32, ) -> Weight;
	fn reject_root_without_end_voting(v: u32, ) -> Weight;
	fn end_voting_period_with_rejected_valid_votes(v: u32, o: u32, ) -> Weight;
	fn end_voting_period_with_approved_invalid_votes(v: u32, o: u32, ) -> Weight;
	fn advance_slot_with_offence(v: u32, ) -> Weight;
	fn advance_slot_without_offence(v: u32, ) -> Weight;
	fn add_challenge(v: u32, ) -> Weight;
	fn admin_resolve_challenge_accepted() -> Weight;
	fn admin_resolve_challenge_rejected() -> Weight;
	fn set_external_validation_threshold() -> Weight;
	fn set_schedule_period() -> Weight;
	fn set_voting_period() -> Weight;
}

/// Weights for pallet_summary using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Summary::NextBlockToProcess` (r:1 w:0)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotingPeriod` (r:0 w:1)
	/// Proof: `Summary::VotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextSlotAtBlock` (r:0 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:0 w:1)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_periods() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `1489`
		// Minimum execution time: 17_480_000 picoseconds.
		Weight::from_parts(18_001_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Summary::TotalIngresses` (r:1 w:1)
	/// Proof: `Summary::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextBlockToProcess` (r:1 w:0)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:1)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotingPeriod` (r:1 w:0)
	/// Proof: `Summary::VotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	/// The range of component `r` is `[1, 2]`.
	fn record_summary_calculation(_v: u32, _r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `424 + r * (33 ±0) + v * (64 ±0)`
		//  Estimated: `19963`
		// Minimum execution time: 62_482_000 picoseconds.
		Weight::from_parts(65_833_111, 19963)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Summary::Roots` (r:1 w:1)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::EthTxLifetimeSecs` (r:1 w:0)
	/// Proof: `EthBridge::EthTxLifetimeSecs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::Instance` (r:1 w:0)
	/// Proof: `EthBridge::Instance` (`max_values`: Some(1), `max_size`: Some(578), added: 1073, mode: `MaxEncodedLen`)
	/// Storage: `Avn::PrimaryCollatorIndexForSending` (r:1 w:1)
	/// Proof: `Avn::PrimaryCollatorIndexForSending` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::Reports` (r:2 w:2)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:2 w:2)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:0)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:0 w:1)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::TxIdToRoot` (r:0 w:1)
	/// Proof: `Summary::TxIdToRoot` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextBlockToProcess` (r:0 w:1)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn approve_root_with_end_voting(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1224 + o * (32 ±0) + v * (74 ±0)`
		//  Estimated: `22431 + o * (2524 ±0) + v * (75 ±0)`
		// Minimum execution time: 292_936_000 picoseconds.
		Weight::from_parts(320_508_157, 22431)
			// Standard Error: 672_302
			.saturating_add(Weight::from_parts(12_778_734, 0).saturating_mul(o.into()))
			.saturating_add(T::DbWeight::get().reads(14_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(T::DbWeight::get().writes(10_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 75).saturating_mul(v.into()))
	}
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:0)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[4, 10]`.
	fn approve_root_without_end_voting(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `641 + v * (64 ±0)`
		//  Estimated: `19963`
		// Minimum execution time: 81_172_000 picoseconds.
		Weight::from_parts(81_802_261, 19963)
			// Standard Error: 7_770
			.saturating_add(Weight::from_parts(135_382, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::Reports` (r:3 w:3)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:3 w:3)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[7, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn reject_root_with_end_voting(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1068 + o * (32 ±0) + v * (64 ±0)`
		//  Estimated: `19963 + o * (2524 ±0) + v * (67 ±0)`
		// Minimum execution time: 221_245_000 picoseconds.
		Weight::from_parts(207_775_011, 19963)
			// Standard Error: 185_777
			.saturating_add(Weight::from_parts(231_839, 0).saturating_mul(v.into()))
			// Standard Error: 431_778
			.saturating_add(Weight::from_parts(17_835_696, 0).saturating_mul(o.into()))
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 67).saturating_mul(v.into()))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:0)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[4, 10]`.
	fn reject_root_without_end_voting(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `618 + v * (64 ±0)`
		//  Estimated: `19963`
		// Minimum execution time: 74_592_000 picoseconds.
		Weight::from_parts(75_774_906, 19963)
			// Standard Error: 8_214
			.saturating_add(Weight::from_parts(43_074, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Summary::VotesRepository` (r:1 w:0)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:1)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::EthTxLifetimeSecs` (r:1 w:0)
	/// Proof: `EthBridge::EthTxLifetimeSecs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::Instance` (r:1 w:0)
	/// Proof: `EthBridge::Instance` (`max_values`: Some(1), `max_size`: Some(578), added: 1073, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Avn::PrimaryCollatorIndexForSending` (r:1 w:1)
	/// Proof: `Avn::PrimaryCollatorIndexForSending` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::Reports` (r:2 w:2)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:2 w:2)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:0)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:0 w:1)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::TxIdToRoot` (r:0 w:1)
	/// Proof: `Summary::TxIdToRoot` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextBlockToProcess` (r:0 w:1)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[7, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn end_voting_period_with_rejected_valid_votes(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1310 + o * (32 ±0) + v * (64 ±0)`
		//  Estimated: `22431 + o * (2524 ±0) + v * (67 ±0)`
		// Minimum execution time: 226_145_000 picoseconds.
		Weight::from_parts(260_940_466, 22431)
			// Standard Error: 430_089
			.saturating_add(Weight::from_parts(11_808_017, 0).saturating_mul(o.into()))
			.saturating_add(T::DbWeight::get().reads(14_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(T::DbWeight::get().writes(9_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 67).saturating_mul(v.into()))
	}
	/// Storage: `Summary::VotesRepository` (r:1 w:0)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Offences::Reports` (r:3 w:3)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:3 w:3)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[7, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn end_voting_period_with_approved_invalid_votes(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1091 + o * (32 ±0) + v * (64 ±0)`
		//  Estimated: `19963 + o * (2524 ±0) + v * (67 ±0)`
		// Minimum execution time: 159_063_000 picoseconds.
		Weight::from_parts(145_877_795, 19963)
			// Standard Error: 105_930
			.saturating_add(Weight::from_parts(11_788, 0).saturating_mul(v.into()))
			// Standard Error: 246_200
			.saturating_add(Weight::from_parts(16_883_665, 0).saturating_mul(o.into()))
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 67).saturating_mul(v.into()))
	}
	/// Storage: `Summary::NextSlotAtBlock` (r:1 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlotsValidator` (r:1 w:1)
	/// Proof: `Summary::CurrentSlotsValidator` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:1 w:0)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:1)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Offences::Reports` (r:1 w:1)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:1 w:1)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[5, 10]`.
	fn advance_slot_with_offence(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `775 + v * (64 ±0)`
		//  Estimated: `17871 + v * (64 ±0)`
		// Minimum execution time: 96_992_000 picoseconds.
		Weight::from_parts(99_639_686, 17871)
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(v.into()))
	}
	/// Storage: `Summary::NextSlotAtBlock` (r:1 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlotsValidator` (r:1 w:1)
	/// Proof: `Summary::CurrentSlotsValidator` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:1 w:0)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:1)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	fn advance_slot_without_offence(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `377 + v * (64 ±0)`
		//  Estimated: `17871`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(38_029_884, 17871)
			// Standard Error: 5_036
			.saturating_add(Weight::from_parts(96_606, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Summary::CurrentSlot` (r:1 w:1)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlotsValidator` (r:1 w:1)
	/// Proof: `Summary::CurrentSlotsValidator` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextSlotAtBlock` (r:1 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Offences::Reports` (r:1 w:1)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:1 w:1)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:1 w:0)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	fn add_challenge(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `775 + v * (64 ±0)`
		//  Estimated: `17871 + v * (64 ±0)`
		// Minimum execution time: 108_923_000 picoseconds.
		Weight::from_parts(109_885_174, 17871)
			// Standard Error: 25_488
			.saturating_add(Weight::from_parts(273_344, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(v.into()))
	}
	/// Storage: `Summary::PendingAdminReviews` (r:1 w:1)
	/// Proof: `Summary::PendingAdminReviews` (`max_values`: None, `max_size`: Some(98), added: 2573, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:1)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationStatus` (r:1 w:1)
	/// Proof: `Summary::ExternalValidationStatus` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::EthTxLifetimeSecs` (r:1 w:0)
	/// Proof: `EthBridge::EthTxLifetimeSecs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::Instance` (r:1 w:0)
	/// Proof: `EthBridge::Instance` (`max_values`: Some(1), `max_size`: Some(578), added: 1073, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Avn::PrimaryCollatorIndexForSending` (r:1 w:1)
	/// Proof: `Avn::PrimaryCollatorIndexForSending` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:0 w:1)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Summary::TxIdToRoot` (r:0 w:1)
	/// Proof: `Summary::TxIdToRoot` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn admin_resolve_challenge_accepted() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1106`
		//  Estimated: `22431`
		// Minimum execution time: 141_993_000 picoseconds.
		Weight::from_parts(148_703_000, 22431)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `Summary::PendingAdminReviews` (r:1 w:1)
	/// Proof: `Summary::PendingAdminReviews` (`max_values`: None, `max_size`: Some(98), added: 2573, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationStatus` (r:1 w:1)
	/// Proof: `Summary::ExternalValidationStatus` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:0 w:1)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn admin_resolve_challenge_rejected() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `557`
		//  Estimated: `3585`
		// Minimum execution time: 47_691_000 picoseconds.
		Weight::from_parts(48_711_000, 3585)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Summary::ExternalValidationThreshold` (r:1 w:1)
	/// Proof: `Summary::ExternalValidationThreshold` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_external_validation_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `1489`
		// Minimum execution time: 16_831_000 picoseconds.
		Weight::from_parts(17_400_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Summary::VotingPeriod` (r:1 w:0)
	/// Proof: `Summary::VotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextBlockToProcess` (r:1 w:0)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextSlotAtBlock` (r:0 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:0 w:1)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_schedule_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `1489`
		// Minimum execution time: 18_401_000 picoseconds.
		Weight::from_parts(18_781_000, 1489)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotingPeriod` (r:1 w:1)
	/// Proof: `Summary::VotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_voting_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `1489`
		// Minimum execution time: 17_921_000 picoseconds.
		Weight::from_parts(18_381_000, 1489)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Summary::NextBlockToProcess` (r:1 w:0)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotingPeriod` (r:0 w:1)
	/// Proof: `Summary::VotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextSlotAtBlock` (r:0 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:0 w:1)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_periods() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `1489`
		// Minimum execution time: 17_480_000 picoseconds.
		Weight::from_parts(18_001_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Summary::TotalIngresses` (r:1 w:1)
	/// Proof: `Summary::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextBlockToProcess` (r:1 w:0)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:1)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotingPeriod` (r:1 w:0)
	/// Proof: `Summary::VotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	/// The range of component `r` is `[1, 2]`.
	fn record_summary_calculation(_v: u32, _r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `424 + r * (33 ±0) + v * (64 ±0)`
		//  Estimated: `19963`
		// Minimum execution time: 62_482_000 picoseconds.
		Weight::from_parts(65_833_111, 19963)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Summary::Roots` (r:1 w:1)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::EthTxLifetimeSecs` (r:1 w:0)
	/// Proof: `EthBridge::EthTxLifetimeSecs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::Instance` (r:1 w:0)
	/// Proof: `EthBridge::Instance` (`max_values`: Some(1), `max_size`: Some(578), added: 1073, mode: `MaxEncodedLen`)
	/// Storage: `Avn::PrimaryCollatorIndexForSending` (r:1 w:1)
	/// Proof: `Avn::PrimaryCollatorIndexForSending` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::Reports` (r:2 w:2)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:2 w:2)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:0)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:0 w:1)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::TxIdToRoot` (r:0 w:1)
	/// Proof: `Summary::TxIdToRoot` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextBlockToProcess` (r:0 w:1)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn approve_root_with_end_voting(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1224 + o * (32 ±0) + v * (74 ±0)`
		//  Estimated: `22431 + o * (2524 ±0) + v * (75 ±0)`
		// Minimum execution time: 292_936_000 picoseconds.
		Weight::from_parts(320_508_157, 22431)
			// Standard Error: 672_302
			.saturating_add(Weight::from_parts(12_778_734, 0).saturating_mul(o.into()))
			.saturating_add(RocksDbWeight::get().reads(14_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(RocksDbWeight::get().writes(10_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 75).saturating_mul(v.into()))
	}
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:0)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[4, 10]`.
	fn approve_root_without_end_voting(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `641 + v * (64 ±0)`
		//  Estimated: `19963`
		// Minimum execution time: 81_172_000 picoseconds.
		Weight::from_parts(81_802_261, 19963)
			// Standard Error: 7_770
			.saturating_add(Weight::from_parts(135_382, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::Reports` (r:3 w:3)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:3 w:3)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[7, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn reject_root_with_end_voting(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1068 + o * (32 ±0) + v * (64 ±0)`
		//  Estimated: `19963 + o * (2524 ±0) + v * (67 ±0)`
		// Minimum execution time: 221_245_000 picoseconds.
		Weight::from_parts(207_775_011, 19963)
			// Standard Error: 185_777
			.saturating_add(Weight::from_parts(231_839, 0).saturating_mul(v.into()))
			// Standard Error: 431_778
			.saturating_add(Weight::from_parts(17_835_696, 0).saturating_mul(o.into()))
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 67).saturating_mul(v.into()))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotesRepository` (r:1 w:1)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:0)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[4, 10]`.
	fn reject_root_without_end_voting(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `618 + v * (64 ±0)`
		//  Estimated: `19963`
		// Minimum execution time: 74_592_000 picoseconds.
		Weight::from_parts(75_774_906, 19963)
			// Standard Error: 8_214
			.saturating_add(Weight::from_parts(43_074, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Summary::VotesRepository` (r:1 w:0)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:1)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::EthTxLifetimeSecs` (r:1 w:0)
	/// Proof: `EthBridge::EthTxLifetimeSecs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::Instance` (r:1 w:0)
	/// Proof: `EthBridge::Instance` (`max_values`: Some(1), `max_size`: Some(578), added: 1073, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Avn::PrimaryCollatorIndexForSending` (r:1 w:1)
	/// Proof: `Avn::PrimaryCollatorIndexForSending` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::Reports` (r:2 w:2)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:2 w:2)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:0)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:0 w:1)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::TxIdToRoot` (r:0 w:1)
	/// Proof: `Summary::TxIdToRoot` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextBlockToProcess` (r:0 w:1)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[7, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn end_voting_period_with_rejected_valid_votes(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1310 + o * (32 ±0) + v * (64 ±0)`
		//  Estimated: `22431 + o * (2524 ±0) + v * (67 ±0)`
		// Minimum execution time: 226_145_000 picoseconds.
		Weight::from_parts(260_940_466, 22431)
			// Standard Error: 430_089
			.saturating_add(Weight::from_parts(11_808_017, 0).saturating_mul(o.into()))
			.saturating_add(RocksDbWeight::get().reads(14_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 67).saturating_mul(v.into()))
	}
	/// Storage: `Summary::VotesRepository` (r:1 w:0)
	/// Proof: `Summary::VotesRepository` (`max_values`: None, `max_size`: Some(16498), added: 18973, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::PendingApproval` (r:1 w:1)
	/// Proof: `Summary::PendingApproval` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Offences::Reports` (r:3 w:3)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:3 w:3)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[7, 10]`.
	/// The range of component `o` is `[1, 2]`.
	fn end_voting_period_with_approved_invalid_votes(v: u32, o: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1091 + o * (32 ±0) + v * (64 ±0)`
		//  Estimated: `19963 + o * (2524 ±0) + v * (67 ±0)`
		// Minimum execution time: 159_063_000 picoseconds.
		Weight::from_parts(145_877_795, 19963)
			// Standard Error: 105_930
			.saturating_add(Weight::from_parts(11_788, 0).saturating_mul(v.into()))
			// Standard Error: 246_200
			.saturating_add(Weight::from_parts(16_883_665, 0).saturating_mul(o.into()))
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(o.into())))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(o.into())))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 67).saturating_mul(v.into()))
	}
	/// Storage: `Summary::NextSlotAtBlock` (r:1 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlotsValidator` (r:1 w:1)
	/// Proof: `Summary::CurrentSlotsValidator` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:1 w:0)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:1)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Offences::Reports` (r:1 w:1)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:1 w:1)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[5, 10]`.
	fn advance_slot_with_offence(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `775 + v * (64 ±0)`
		//  Estimated: `17871 + v * (64 ±0)`
		// Minimum execution time: 96_992_000 picoseconds.
		Weight::from_parts(99_639_686, 17871)
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(v.into()))
	}
	/// Storage: `Summary::NextSlotAtBlock` (r:1 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlotsValidator` (r:1 w:1)
	/// Proof: `Summary::CurrentSlotsValidator` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:1 w:0)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlot` (r:1 w:1)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	fn advance_slot_without_offence(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `377 + v * (64 ±0)`
		//  Estimated: `17871`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(38_029_884, 17871)
			// Standard Error: 5_036
			.saturating_add(Weight::from_parts(96_606, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Summary::CurrentSlot` (r:1 w:1)
	/// Proof: `Summary::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::CurrentSlotsValidator` (r:1 w:1)
	/// Proof: `Summary::CurrentSlotsValidator` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextSlotAtBlock` (r:1 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Offences::Reports` (r:1 w:1)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:1 w:1)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SlotOfLastPublishedSummary` (r:1 w:0)
	/// Proof: `Summary::SlotOfLastPublishedSummary` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	fn add_challenge(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `775 + v * (64 ±0)`
		//  Estimated: `17871 + v * (64 ±0)`
		// Minimum execution time: 108_923_000 picoseconds.
		Weight::from_parts(109_885_174, 17871)
			// Standard Error: 25_488
			.saturating_add(Weight::from_parts(273_344, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(v.into()))
	}
	/// Storage: `Summary::PendingAdminReviews` (r:1 w:1)
	/// Proof: `Summary::PendingAdminReviews` (`max_values`: None, `max_size`: Some(98), added: 2573, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:1)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationStatus` (r:1 w:1)
	/// Proof: `Summary::ExternalValidationStatus` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::EthTxLifetimeSecs` (r:1 w:0)
	/// Proof: `EthBridge::EthTxLifetimeSecs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::Instance` (r:1 w:0)
	/// Proof: `EthBridge::Instance` (`max_values`: Some(1), `max_size`: Some(578), added: 1073, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Avn::PrimaryCollatorIndexForSending` (r:1 w:1)
	/// Proof: `Avn::PrimaryCollatorIndexForSending` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:0 w:1)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Summary::TxIdToRoot` (r:0 w:1)
	/// Proof: `Summary::TxIdToRoot` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn admin_resolve_challenge_accepted() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1106`
		//  Estimated: `22431`
		// Minimum execution time: 141_993_000 picoseconds.
		Weight::from_parts(148_703_000, 22431)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: `Summary::PendingAdminReviews` (r:1 w:1)
	/// Proof: `Summary::PendingAdminReviews` (`max_values`: None, `max_size`: Some(98), added: 2573, mode: `MaxEncodedLen`)
	/// Storage: `Summary::Roots` (r:1 w:0)
	/// Proof: `Summary::Roots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationStatus` (r:1 w:1)
	/// Proof: `Summary::ExternalValidationStatus` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:0 w:1)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn admin_resolve_challenge_rejected() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `557`
		//  Estimated: `3585`
		// Minimum execution time: 47_691_000 picoseconds.
		Weight::from_parts(48_711_000, 3585)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Summary::ExternalValidationThreshold` (r:1 w:1)
	/// Proof: `Summary::ExternalValidationThreshold` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_external_validation_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `1489`
		// Minimum execution time: 16_831_000 picoseconds.
		Weight::from_parts(17_400_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Summary::VotingPeriod` (r:1 w:0)
	/// Proof: `Summary::VotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextBlockToProcess` (r:1 w:0)
	/// Proof: `Summary::NextBlockToProcess` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::NextSlotAtBlock` (r:0 w:1)
	/// Proof: `Summary::NextSlotAtBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::SchedulePeriod` (r:0 w:1)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_schedule_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `1489`
		// Minimum execution time: 18_401_000 picoseconds.
		Weight::from_parts(18_781_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Summary::SchedulePeriod` (r:1 w:0)
	/// Proof: `Summary::SchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Summary::VotingPeriod` (r:1 w:1)
	/// Proof: `Summary::VotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_voting_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `1489`
		// Minimum execution time: 17_921_000 picoseconds.
		Weight::from_parts(18_381_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
