//! Autogenerated weights for pallet_nft_manager
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-04-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-1-153`, CPU: `AMD EPYC 7R32`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./avn-parachain-collator
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// frame-weight-template.hbs
// --pallet
// pallet_nft_manager
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// nft_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_nft_manager.
pub trait WeightInfo {
	fn mint_single_nft(r: u32, ) -> Weight;
	fn signed_mint_single_nft(r: u32, ) -> Weight;
	fn list_nft_open_for_sale() -> Weight;
	fn signed_list_nft_open_for_sale() -> Weight;
	fn signed_transfer_fiat_nft() -> Weight;
	fn signed_cancel_list_fiat_nft() -> Weight;
	fn proxy_signed_mint_single_nft(r: u32, ) -> Weight;
	fn proxy_signed_list_nft_open_for_sale() -> Weight;
	fn proxy_signed_transfer_fiat_nft() -> Weight;
	fn proxy_signed_cancel_list_fiat_nft() -> Weight;
	fn proxy_signed_create_batch(r: u32, ) -> Weight;
	fn proxy_signed_mint_batch_nft() -> Weight;
	fn proxy_signed_list_batch_for_sale() -> Weight;
	fn proxy_signed_end_batch_sale() -> Weight;
}

/// Weights for pallet_nft_manager using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `NftManager::UsedExternalReferences` (r:1 w:1)
	/// Proof: `NftManager::UsedExternalReferences` (`max_values`: None, `max_size`: Some(1043), added: 3518, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextSingleNftUniqueId` (r:1 w:1)
	/// Proof: `NftManager::NextSingleNftUniqueId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextInfoId` (r:1 w:1)
	/// Proof: `NftManager::NextInfoId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftInfos` (r:0 w:1)
	/// Proof: `NftManager::NftInfos` (`max_values`: None, `max_size`: Some(559), added: 3034, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 16]`.
	fn mint_single_nft(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `4644`
		// Minimum execution time: 40_201_000 picoseconds.
		Weight::from_parts(40_766_466, 4644)
			// Standard Error: 2_754
			.saturating_add(Weight::from_parts(163_339, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `NftManager::UsedExternalReferences` (r:1 w:1)
	/// Proof: `NftManager::UsedExternalReferences` (`max_values`: None, `max_size`: Some(1043), added: 3518, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextSingleNftUniqueId` (r:1 w:1)
	/// Proof: `NftManager::NextSingleNftUniqueId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextInfoId` (r:1 w:1)
	/// Proof: `NftManager::NextInfoId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftInfos` (r:0 w:1)
	/// Proof: `NftManager::NftInfos` (`max_values`: None, `max_size`: Some(559), added: 3034, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 16]`.
	fn signed_mint_single_nft(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `4644`
		// Minimum execution time: 151_583_000 picoseconds.
		Weight::from_parts(153_701_464, 4644)
			// Standard Error: 13_226
			.saturating_add(Weight::from_parts(600_114, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::NftOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn list_nft_open_for_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `249`
		//  Estimated: `4644`
		// Minimum execution time: 33_141_000 picoseconds.
		Weight::from_parts(33_941_000, 4644)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::NftOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn signed_list_nft_open_for_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `249`
		//  Estimated: `4644`
		// Minimum execution time: 145_323_000 picoseconds.
		Weight::from_parts(146_594_000, 4644)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::NftOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::NftOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn signed_transfer_fiat_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `4644`
		// Minimum execution time: 157_164_000 picoseconds.
		Weight::from_parts(158_434_000, 4644)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::NftOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::NftOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn signed_cancel_list_fiat_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `4644`
		// Minimum execution time: 155_284_000 picoseconds.
		Weight::from_parts(157_193_000, 4644)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::UsedExternalReferences` (r:1 w:1)
	/// Proof: `NftManager::UsedExternalReferences` (`max_values`: None, `max_size`: Some(1043), added: 3518, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextSingleNftUniqueId` (r:1 w:1)
	/// Proof: `NftManager::NextSingleNftUniqueId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextInfoId` (r:1 w:1)
	/// Proof: `NftManager::NextInfoId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftInfos` (r:0 w:1)
	/// Proof: `NftManager::NftInfos` (`max_values`: None, `max_size`: Some(559), added: 3034, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 16]`.
	fn proxy_signed_mint_single_nft(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `4644`
		// Minimum execution time: 158_333_000 picoseconds.
		Weight::from_parts(159_865_720, 4644)
			// Standard Error: 15_063
			.saturating_add(Weight::from_parts(784_112, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::NftOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn proxy_signed_list_nft_open_for_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `249`
		//  Estimated: `4644`
		// Minimum execution time: 153_483_000 picoseconds.
		Weight::from_parts(155_034_000, 4644)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::NftOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::NftOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn proxy_signed_transfer_fiat_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `4644`
		// Minimum execution time: 164_094_000 picoseconds.
		Weight::from_parts(166_023_000, 4644)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::NftOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::NftOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn proxy_signed_cancel_list_fiat_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `4644`
		// Minimum execution time: 164_614_000 picoseconds.
		Weight::from_parts(165_823_000, 4644)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::BatchNonces` (r:1 w:1)
	/// Proof: `NftManager::BatchNonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextSingleNftUniqueId` (r:1 w:1)
	/// Proof: `NftManager::NextSingleNftUniqueId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::BatchInfoId` (r:1 w:1)
	/// Proof: `NftManager::BatchInfoId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextInfoId` (r:1 w:1)
	/// Proof: `NftManager::NextInfoId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftInfos` (r:0 w:1)
	/// Proof: `NftManager::NftInfos` (`max_values`: None, `max_size`: Some(559), added: 3034, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 16384]`.
	fn proxy_signed_create_batch(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3545`
		// Minimum execution time: 167_494_000 picoseconds.
		Weight::from_parts(170_149_470, 3545)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `NftManager::BatchInfoId` (r:1 w:0)
	/// Proof: `NftManager::BatchInfoId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::BatchOpenForSale` (r:1 w:0)
	/// Proof: `NftManager::BatchOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftInfos` (r:1 w:0)
	/// Proof: `NftManager::NftInfos` (`max_values`: None, `max_size`: Some(559), added: 3034, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftBatches` (r:1 w:1)
	/// Proof: `NftManager::NftBatches` (`max_values`: None, `max_size`: Some(524340), added: 526815, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::UsedExternalReferences` (r:1 w:1)
	/// Proof: `NftManager::UsedExternalReferences` (`max_values`: None, `max_size`: Some(1043), added: 3518, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn proxy_signed_mint_batch_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `840`
		//  Estimated: `527805`
		// Minimum execution time: 201_565_000 picoseconds.
		Weight::from_parts(202_694_000, 527805)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `NftManager::BatchInfoId` (r:1 w:0)
	/// Proof: `NftManager::BatchInfoId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::BatchNonces` (r:1 w:1)
	/// Proof: `NftManager::BatchNonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftInfos` (r:1 w:0)
	/// Proof: `NftManager::NftInfos` (`max_values`: None, `max_size`: Some(559), added: 3034, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftBatches` (r:1 w:0)
	/// Proof: `NftManager::NftBatches` (`max_values`: None, `max_size`: Some(524340), added: 526815, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::BatchOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::BatchOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn proxy_signed_list_batch_for_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `810`
		//  Estimated: `527805`
		// Minimum execution time: 169_114_000 picoseconds.
		Weight::from_parts(170_654_000, 527805)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::BatchInfoId` (r:1 w:0)
	/// Proof: `NftManager::BatchInfoId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::BatchOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::BatchOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::BatchNonces` (r:1 w:1)
	/// Proof: `NftManager::BatchNonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftInfos` (r:1 w:0)
	/// Proof: `NftManager::NftInfos` (`max_values`: None, `max_size`: Some(559), added: 3034, mode: `MaxEncodedLen`)
	fn proxy_signed_end_batch_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `884`
		//  Estimated: `4024`
		// Minimum execution time: 178_674_000 picoseconds.
		Weight::from_parts(180_314_000, 4024)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `NftManager::UsedExternalReferences` (r:1 w:1)
	/// Proof: `NftManager::UsedExternalReferences` (`max_values`: None, `max_size`: Some(1043), added: 3518, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextSingleNftUniqueId` (r:1 w:1)
	/// Proof: `NftManager::NextSingleNftUniqueId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextInfoId` (r:1 w:1)
	/// Proof: `NftManager::NextInfoId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftInfos` (r:0 w:1)
	/// Proof: `NftManager::NftInfos` (`max_values`: None, `max_size`: Some(559), added: 3034, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 16]`.
	fn mint_single_nft(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `4644`
		// Minimum execution time: 40_201_000 picoseconds.
		Weight::from_parts(40_766_466, 4644)
			// Standard Error: 2_754
			.saturating_add(Weight::from_parts(163_339, 0).saturating_mul(r.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `NftManager::UsedExternalReferences` (r:1 w:1)
	/// Proof: `NftManager::UsedExternalReferences` (`max_values`: None, `max_size`: Some(1043), added: 3518, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextSingleNftUniqueId` (r:1 w:1)
	/// Proof: `NftManager::NextSingleNftUniqueId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextInfoId` (r:1 w:1)
	/// Proof: `NftManager::NextInfoId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftInfos` (r:0 w:1)
	/// Proof: `NftManager::NftInfos` (`max_values`: None, `max_size`: Some(559), added: 3034, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 16]`.
	fn signed_mint_single_nft(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `4644`
		// Minimum execution time: 151_583_000 picoseconds.
		Weight::from_parts(153_701_464, 4644)
			// Standard Error: 13_226
			.saturating_add(Weight::from_parts(600_114, 0).saturating_mul(r.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::NftOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn list_nft_open_for_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `249`
		//  Estimated: `4644`
		// Minimum execution time: 33_141_000 picoseconds.
		Weight::from_parts(33_941_000, 4644)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::NftOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn signed_list_nft_open_for_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `249`
		//  Estimated: `4644`
		// Minimum execution time: 145_323_000 picoseconds.
		Weight::from_parts(146_594_000, 4644)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::NftOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::NftOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn signed_transfer_fiat_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `4644`
		// Minimum execution time: 157_164_000 picoseconds.
		Weight::from_parts(158_434_000, 4644)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::NftOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::NftOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn signed_cancel_list_fiat_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `4644`
		// Minimum execution time: 155_284_000 picoseconds.
		Weight::from_parts(157_193_000, 4644)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::UsedExternalReferences` (r:1 w:1)
	/// Proof: `NftManager::UsedExternalReferences` (`max_values`: None, `max_size`: Some(1043), added: 3518, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextSingleNftUniqueId` (r:1 w:1)
	/// Proof: `NftManager::NextSingleNftUniqueId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextInfoId` (r:1 w:1)
	/// Proof: `NftManager::NextInfoId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftInfos` (r:0 w:1)
	/// Proof: `NftManager::NftInfos` (`max_values`: None, `max_size`: Some(559), added: 3034, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 16]`.
	fn proxy_signed_mint_single_nft(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `4644`
		// Minimum execution time: 158_333_000 picoseconds.
		Weight::from_parts(159_865_720, 4644)
			// Standard Error: 15_063
			.saturating_add(Weight::from_parts(784_112, 0).saturating_mul(r.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::NftOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn proxy_signed_list_nft_open_for_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `249`
		//  Estimated: `4644`
		// Minimum execution time: 153_483_000 picoseconds.
		Weight::from_parts(155_034_000, 4644)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::NftOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::NftOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn proxy_signed_transfer_fiat_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `4644`
		// Minimum execution time: 164_094_000 picoseconds.
		Weight::from_parts(166_023_000, 4644)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::NftOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::NftOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn proxy_signed_cancel_list_fiat_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `4644`
		// Minimum execution time: 164_614_000 picoseconds.
		Weight::from_parts(165_823_000, 4644)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::BatchNonces` (r:1 w:1)
	/// Proof: `NftManager::BatchNonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextSingleNftUniqueId` (r:1 w:1)
	/// Proof: `NftManager::NextSingleNftUniqueId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::BatchInfoId` (r:1 w:1)
	/// Proof: `NftManager::BatchInfoId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NextInfoId` (r:1 w:1)
	/// Proof: `NftManager::NextInfoId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftInfos` (r:0 w:1)
	/// Proof: `NftManager::NftInfos` (`max_values`: None, `max_size`: Some(559), added: 3034, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 16384]`.
	fn proxy_signed_create_batch(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3545`
		// Minimum execution time: 167_494_000 picoseconds.
		Weight::from_parts(170_149_470, 3545)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `NftManager::BatchInfoId` (r:1 w:0)
	/// Proof: `NftManager::BatchInfoId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::BatchOpenForSale` (r:1 w:0)
	/// Proof: `NftManager::BatchOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftInfos` (r:1 w:0)
	/// Proof: `NftManager::NftInfos` (`max_values`: None, `max_size`: Some(559), added: 3034, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftBatches` (r:1 w:1)
	/// Proof: `NftManager::NftBatches` (`max_values`: None, `max_size`: Some(524340), added: 526815, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::UsedExternalReferences` (r:1 w:1)
	/// Proof: `NftManager::UsedExternalReferences` (`max_values`: None, `max_size`: Some(1043), added: 3518, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::Nfts` (r:1 w:1)
	/// Proof: `NftManager::Nfts` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn proxy_signed_mint_batch_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `840`
		//  Estimated: `527805`
		// Minimum execution time: 201_565_000 picoseconds.
		Weight::from_parts(202_694_000, 527805)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `NftManager::BatchInfoId` (r:1 w:0)
	/// Proof: `NftManager::BatchInfoId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::BatchNonces` (r:1 w:1)
	/// Proof: `NftManager::BatchNonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftInfos` (r:1 w:0)
	/// Proof: `NftManager::NftInfos` (`max_values`: None, `max_size`: Some(559), added: 3034, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftBatches` (r:1 w:0)
	/// Proof: `NftManager::NftBatches` (`max_values`: None, `max_size`: Some(524340), added: 526815, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::BatchOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::BatchOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn proxy_signed_list_batch_for_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `810`
		//  Estimated: `527805`
		// Minimum execution time: 169_114_000 picoseconds.
		Weight::from_parts(170_654_000, 527805)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NftManager::BatchInfoId` (r:1 w:0)
	/// Proof: `NftManager::BatchInfoId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::BatchOpenForSale` (r:1 w:1)
	/// Proof: `NftManager::BatchOpenForSale` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::BatchNonces` (r:1 w:1)
	/// Proof: `NftManager::BatchNonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `NftManager::NftInfos` (r:1 w:0)
	/// Proof: `NftManager::NftInfos` (`max_values`: None, `max_size`: Some(559), added: 3034, mode: `MaxEncodedLen`)
	fn proxy_signed_end_batch_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `884`
		//  Estimated: `4024`
		// Minimum execution time: 178_674_000 picoseconds.
		Weight::from_parts(180_314_000, 4024)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}