//! Autogenerated weights for pallet_validators_manager
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-04-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-1-153`, CPU: `AMD EPYC 7R32`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./avn-parachain-collator
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// frame-weight-template.hbs
// --pallet
// pallet_validators_manager
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// validators_manager_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_validators_manager.
pub trait WeightInfo {
	fn add_collator() -> Weight;
	fn remove_validator(v: u32, ) -> Weight;
	fn rotate_validator_ethereum_key() -> Weight;
}

/// Weights for pallet_validators_manager using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ValidatorsManager::ValidatorAccountIds` (r:1 w:0)
	/// Proof: `ValidatorsManager::ValidatorAccountIds` (`max_values`: Some(1), `max_size`: Some(8194), added: 8689, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::EthereumPublicKeys` (r:1 w:1)
	/// Proof: `ValidatorsManager::EthereumPublicKeys` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `Session::NextKeys` (r:1 w:0)
	/// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ValidatorsManager::ValidatorActions` (r:1 w:1)
	/// Proof: `ValidatorsManager::ValidatorActions` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::MinCollatorStake` (r:1 w:0)
	/// Proof: `ParachainStaking::MinCollatorStake` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::CandidateInfo` (r:1 w:0)
	/// Proof: `ParachainStaking::CandidateInfo` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::EthTxLifetimeSecs` (r:1 w:0)
	/// Proof: `EthBridge::EthTxLifetimeSecs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::Instance` (r:1 w:0)
	/// Proof: `EthBridge::Instance` (`max_values`: Some(1), `max_size`: Some(578), added: 1073, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Avn::PrimaryCollatorIndexForSending` (r:1 w:1)
	/// Proof: `Avn::PrimaryCollatorIndexForSending` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::TotalIngresses` (r:1 w:1)
	/// Proof: `ValidatorsManager::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::TransactionIdToAction` (r:0 w:1)
	/// Proof: `ValidatorsManager::TransactionIdToAction` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::AccountIdToEthereumKeys` (r:0 w:1)
	/// Proof: `ValidatorsManager::AccountIdToEthereumKeys` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::PendingRegistrationDeposits` (r:0 w:1)
	/// Proof: `ValidatorsManager::PendingRegistrationDeposits` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn add_collator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1771`
		//  Estimated: `22431`
		// Minimum execution time: 178_624_000 picoseconds.
		Weight::from_parts(181_794_000, 22431)
			.saturating_add(T::DbWeight::get().reads(15_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: `ValidatorsManager::ValidatorAccountIds` (r:1 w:0)
	/// Proof: `ValidatorsManager::ValidatorAccountIds` (`max_values`: Some(1), `max_size`: Some(8194), added: 8689, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::ValidatorActions` (r:1 w:1)
	/// Proof: `ValidatorsManager::ValidatorActions` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::AccountIdToEthereumKeys` (r:1 w:0)
	/// Proof: `ValidatorsManager::AccountIdToEthereumKeys` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:0)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::RequestQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestQueue` (`max_values`: Some(1), `max_size`: Some(79002), added: 79497, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::TotalIngresses` (r:1 w:1)
	/// Proof: `ValidatorsManager::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::TransactionIdToAction` (r:0 w:1)
	/// Proof: `ValidatorsManager::TransactionIdToAction` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	fn remove_validator(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `739 + v * (202 ±0)`
		//  Estimated: `80487`
		// Minimum execution time: 101_052_000 picoseconds.
		Weight::from_parts(91_513_897, 80487)
			// Standard Error: 16_548
			.saturating_add(Weight::from_parts(3_823_844, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `ValidatorsManager::EthereumPublicKeys` (r:2 w:2)
	/// Proof: `ValidatorsManager::EthereumPublicKeys` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::AccountIdToEthereumKeys` (r:0 w:1)
	/// Proof: `ValidatorsManager::AccountIdToEthereumKeys` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	fn rotate_validator_ethereum_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `310`
		//  Estimated: `6102`
		// Minimum execution time: 32_400_000 picoseconds.
		Weight::from_parts(32_960_000, 6102)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ValidatorsManager::ValidatorAccountIds` (r:1 w:0)
	/// Proof: `ValidatorsManager::ValidatorAccountIds` (`max_values`: Some(1), `max_size`: Some(8194), added: 8689, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::EthereumPublicKeys` (r:1 w:1)
	/// Proof: `ValidatorsManager::EthereumPublicKeys` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `Session::NextKeys` (r:1 w:0)
	/// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ValidatorsManager::ValidatorActions` (r:1 w:1)
	/// Proof: `ValidatorsManager::ValidatorActions` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::MinCollatorStake` (r:1 w:0)
	/// Proof: `ParachainStaking::MinCollatorStake` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::CandidateInfo` (r:1 w:0)
	/// Proof: `ParachainStaking::CandidateInfo` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::EthTxLifetimeSecs` (r:1 w:0)
	/// Proof: `EthBridge::EthTxLifetimeSecs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::Instance` (r:1 w:0)
	/// Proof: `EthBridge::Instance` (`max_values`: Some(1), `max_size`: Some(578), added: 1073, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Avn::PrimaryCollatorIndexForSending` (r:1 w:1)
	/// Proof: `Avn::PrimaryCollatorIndexForSending` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::TotalIngresses` (r:1 w:1)
	/// Proof: `ValidatorsManager::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::TransactionIdToAction` (r:0 w:1)
	/// Proof: `ValidatorsManager::TransactionIdToAction` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::AccountIdToEthereumKeys` (r:0 w:1)
	/// Proof: `ValidatorsManager::AccountIdToEthereumKeys` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::PendingRegistrationDeposits` (r:0 w:1)
	/// Proof: `ValidatorsManager::PendingRegistrationDeposits` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn add_collator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1771`
		//  Estimated: `22431`
		// Minimum execution time: 178_624_000 picoseconds.
		Weight::from_parts(181_794_000, 22431)
			.saturating_add(RocksDbWeight::get().reads(15_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
	/// Storage: `ValidatorsManager::ValidatorAccountIds` (r:1 w:0)
	/// Proof: `ValidatorsManager::ValidatorAccountIds` (`max_values`: Some(1), `max_size`: Some(8194), added: 8689, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::ValidatorActions` (r:1 w:1)
	/// Proof: `ValidatorsManager::ValidatorActions` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::AccountIdToEthereumKeys` (r:1 w:0)
	/// Proof: `ValidatorsManager::AccountIdToEthereumKeys` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:0)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::RequestQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestQueue` (`max_values`: Some(1), `max_size`: Some(79002), added: 79497, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::TotalIngresses` (r:1 w:1)
	/// Proof: `ValidatorsManager::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::TransactionIdToAction` (r:0 w:1)
	/// Proof: `ValidatorsManager::TransactionIdToAction` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	fn remove_validator(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `739 + v * (202 ±0)`
		//  Estimated: `80487`
		// Minimum execution time: 101_052_000 picoseconds.
		Weight::from_parts(91_513_897, 80487)
			// Standard Error: 16_548
			.saturating_add(Weight::from_parts(3_823_844, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `ValidatorsManager::EthereumPublicKeys` (r:2 w:2)
	/// Proof: `ValidatorsManager::EthereumPublicKeys` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorsManager::AccountIdToEthereumKeys` (r:0 w:1)
	/// Proof: `ValidatorsManager::AccountIdToEthereumKeys` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	fn rotate_validator_ethereum_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `310`
		//  Estimated: `6102`
		// Minimum execution time: 32_400_000 picoseconds.
		Weight::from_parts(32_960_000, 6102)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}