//! Autogenerated weights for pallet_ethereum_events
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-04-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-1-153`, CPU: `AMD EPYC 7R32`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./avn-parachain-collator
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// frame-weight-template.hbs
// --pallet
// pallet_ethereum_events
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// eth_events_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_ethereum_events.
pub trait WeightInfo {
	fn add_ethereum_log(u: u32, e: u32, ) -> Weight;
	fn signed_add_ethereum_log(u: u32, e: u32, ) -> Weight;
	fn set_nft_contract_map_storage() -> Weight;
	fn submit_checkevent_result(v: u32, u: u32, ) -> Weight;
	fn process_event_with_successful_challenge(v: u32, e: u32, ) -> Weight;
	fn process_event_without_successful_challenge(v: u32, e: u32, ) -> Weight;
	fn challenge_event(v: u32, e: u32, c: u32, ) -> Weight;
	fn set_event_challenge_period() -> Weight;
}

/// Weights for pallet_ethereum_events using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `EthBridge::ProcessedEthereumEvents` (r:1 w:0)
	/// Proof: `EthBridge::ProcessedEthereumEvents` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::UncheckedEvents` (r:1 w:1)
	/// Proof: `EthereumEvents::UncheckedEvents` (`max_values`: Some(1), `max_size`: Some(38002), added: 38497, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::EventsPendingChallenge` (r:1 w:0)
	/// Proof: `EthereumEvents::EventsPendingChallenge` (`max_values`: Some(1), `max_size`: Some(62401), added: 62896, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::TotalIngresses` (r:1 w:1)
	/// Proof: `EthereumEvents::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// The range of component `u` is `[1, 499]`.
	/// The range of component `e` is `[1, 49]`.
	fn add_ethereum_log(u: u32, e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `342 + e * (122 ±0) + u * (76 ±0)`
		//  Estimated: `63886`
		// Minimum execution time: 53_021_000 picoseconds.
		Weight::from_parts(40_398_795, 63886)
			// Standard Error: 460
			.saturating_add(Weight::from_parts(91_541, 0).saturating_mul(u.into()))
			// Standard Error: 4_692
			.saturating_add(Weight::from_parts(217_619, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `EthereumEvents::ProxyNonces` (r:1 w:1)
	/// Proof: `EthereumEvents::ProxyNonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ProcessedEthereumEvents` (r:1 w:0)
	/// Proof: `EthBridge::ProcessedEthereumEvents` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::UncheckedEvents` (r:1 w:1)
	/// Proof: `EthereumEvents::UncheckedEvents` (`max_values`: Some(1), `max_size`: Some(38002), added: 38497, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::EventsPendingChallenge` (r:1 w:0)
	/// Proof: `EthereumEvents::EventsPendingChallenge` (`max_values`: Some(1), `max_size`: Some(62401), added: 62896, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::TotalIngresses` (r:1 w:1)
	/// Proof: `EthereumEvents::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// The range of component `u` is `[1, 499]`.
	/// The range of component `e` is `[1, 49]`.
	fn signed_add_ethereum_log(u: u32, e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `342 + e * (122 ±0) + u * (76 ±0)`
		//  Estimated: `63886`
		// Minimum execution time: 163_704_000 picoseconds.
		Weight::from_parts(151_754_295, 63886)
			// Standard Error: 1_029
			.saturating_add(Weight::from_parts(98_091, 0).saturating_mul(u.into()))
			// Standard Error: 10_488
			.saturating_add(Weight::from_parts(224_756, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `EthereumEvents::NftT1Contracts` (r:0 w:1)
	/// Proof: `EthereumEvents::NftT1Contracts` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn set_nft_contract_map_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_051_000 picoseconds.
		Weight::from_parts(7_280_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::UncheckedEvents` (r:1 w:1)
	/// Proof: `EthereumEvents::UncheckedEvents` (`max_values`: Some(1), `max_size`: Some(38002), added: 38497, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::EventChallengePeriod` (r:1 w:0)
	/// Proof: `EthereumEvents::EventChallengePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::QuorumFactor` (r:1 w:0)
	/// Proof: `EthereumEvents::QuorumFactor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::EventsPendingChallenge` (r:1 w:1)
	/// Proof: `EthereumEvents::EventsPendingChallenge` (`max_values`: Some(1), `max_size`: Some(62401), added: 62896, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[1, 10]`.
	/// The range of component `u` is `[1, 499]`.
	fn submit_checkevent_result(_v: u32, u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `391 + u * (76 ±0) + v * (64 ±0)`
		//  Estimated: `63886`
		// Minimum execution time: 41_531_000 picoseconds.
		Weight::from_parts(42_073_207, 63886)
			// Standard Error: 2_457
			.saturating_add(Weight::from_parts(512_288, 0).saturating_mul(u.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::EventsPendingChallenge` (r:1 w:1)
	/// Proof: `EthereumEvents::EventsPendingChallenge` (`max_values`: Some(1), `max_size`: Some(62401), added: 62896, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::QuorumFactor` (r:1 w:0)
	/// Proof: `EthereumEvents::QuorumFactor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::Challenges` (r:1 w:0)
	/// Proof: `EthereumEvents::Challenges` (`max_values`: None, `max_size`: Some(1681), added: 4156, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ProcessedEthereumEvents` (r:1 w:0)
	/// Proof: `EthBridge::ProcessedEthereumEvents` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Session::Validators` (r:1 w:0)
	/// Proof: `Session::Validators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::Reports` (r:1 w:1)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:1 w:1)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[1, 10]`.
	/// The range of component `e` is `[1, 49]`.
	fn process_event_with_successful_challenge(v: u32, e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1144 + e * (122 ±0) + v * (74 ±0)`
		//  Estimated: `63886 + e * (122 ±0) + v * (75 ±0)`
		// Minimum execution time: 117_273_000 picoseconds.
		Weight::from_parts(117_615_544, 63886)
			// Standard Error: 26_620
			.saturating_add(Weight::from_parts(72_697, 0).saturating_mul(v.into()))
			// Standard Error: 5_205
			.saturating_add(Weight::from_parts(1_049_331, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 122).saturating_mul(e.into()))
			.saturating_add(Weight::from_parts(0, 75).saturating_mul(v.into()))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::EventsPendingChallenge` (r:1 w:1)
	/// Proof: `EthereumEvents::EventsPendingChallenge` (`max_values`: Some(1), `max_size`: Some(62401), added: 62896, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::QuorumFactor` (r:1 w:0)
	/// Proof: `EthereumEvents::QuorumFactor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::Challenges` (r:1 w:1)
	/// Proof: `EthereumEvents::Challenges` (`max_values`: None, `max_size`: Some(1681), added: 4156, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ProcessedEthereumEvents` (r:1 w:1)
	/// Proof: `EthBridge::ProcessedEthereumEvents` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Session::Validators` (r:1 w:0)
	/// Proof: `Session::Validators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::Reports` (r:1 w:1)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:1 w:1)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[1, 10]`.
	/// The range of component `e` is `[1, 49]`.
	fn process_event_without_successful_challenge(v: u32, e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1155 + e * (122 ±0) + v * (64 ±0)`
		//  Estimated: `63886 + e * (122 ±0) + v * (64 ±0)`
		// Minimum execution time: 123_203_000 picoseconds.
		Weight::from_parts(123_113_850, 63886)
			// Standard Error: 31_428
			.saturating_add(Weight::from_parts(138_834, 0).saturating_mul(v.into()))
			// Standard Error: 6_145
			.saturating_add(Weight::from_parts(1_065_221, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(Weight::from_parts(0, 122).saturating_mul(e.into()))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(v.into()))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::EventsPendingChallenge` (r:1 w:0)
	/// Proof: `EthereumEvents::EventsPendingChallenge` (`max_values`: Some(1), `max_size`: Some(62401), added: 62896, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::Challenges` (r:1 w:1)
	/// Proof: `EthereumEvents::Challenges` (`max_values`: None, `max_size`: Some(1681), added: 4156, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	/// The range of component `e` is `[1, 49]`.
	/// The range of component `c` is `[1, 49]`.
	fn challenge_event(v: u32, e: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `551 + c * (32 ±0) + e * (122 ±0) + v * (64 ±0)`
		//  Estimated: `63886`
		// Minimum execution time: 47_321_000 picoseconds.
		Weight::from_parts(46_092_838, 63886)
			// Standard Error: 11_322
			.saturating_add(Weight::from_parts(62_677, 0).saturating_mul(v.into()))
			// Standard Error: 1_740
			.saturating_add(Weight::from_parts(255_671, 0).saturating_mul(e.into()))
			// Standard Error: 1_740
			.saturating_add(Weight::from_parts(31_400, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `EthereumEvents::EventChallengePeriod` (r:0 w:1)
	/// Proof: `EthereumEvents::EventChallengePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_event_challenge_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_440_000 picoseconds.
		Weight::from_parts(9_640_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `EthBridge::ProcessedEthereumEvents` (r:1 w:0)
	/// Proof: `EthBridge::ProcessedEthereumEvents` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::UncheckedEvents` (r:1 w:1)
	/// Proof: `EthereumEvents::UncheckedEvents` (`max_values`: Some(1), `max_size`: Some(38002), added: 38497, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::EventsPendingChallenge` (r:1 w:0)
	/// Proof: `EthereumEvents::EventsPendingChallenge` (`max_values`: Some(1), `max_size`: Some(62401), added: 62896, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::TotalIngresses` (r:1 w:1)
	/// Proof: `EthereumEvents::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// The range of component `u` is `[1, 499]`.
	/// The range of component `e` is `[1, 49]`.
	fn add_ethereum_log(u: u32, e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `342 + e * (122 ±0) + u * (76 ±0)`
		//  Estimated: `63886`
		// Minimum execution time: 53_021_000 picoseconds.
		Weight::from_parts(40_398_795, 63886)
			// Standard Error: 460
			.saturating_add(Weight::from_parts(91_541, 0).saturating_mul(u.into()))
			// Standard Error: 4_692
			.saturating_add(Weight::from_parts(217_619, 0).saturating_mul(e.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `EthereumEvents::ProxyNonces` (r:1 w:1)
	/// Proof: `EthereumEvents::ProxyNonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ProcessedEthereumEvents` (r:1 w:0)
	/// Proof: `EthBridge::ProcessedEthereumEvents` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::UncheckedEvents` (r:1 w:1)
	/// Proof: `EthereumEvents::UncheckedEvents` (`max_values`: Some(1), `max_size`: Some(38002), added: 38497, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::EventsPendingChallenge` (r:1 w:0)
	/// Proof: `EthereumEvents::EventsPendingChallenge` (`max_values`: Some(1), `max_size`: Some(62401), added: 62896, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::TotalIngresses` (r:1 w:1)
	/// Proof: `EthereumEvents::TotalIngresses` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// The range of component `u` is `[1, 499]`.
	/// The range of component `e` is `[1, 49]`.
	fn signed_add_ethereum_log(u: u32, e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `342 + e * (122 ±0) + u * (76 ±0)`
		//  Estimated: `63886`
		// Minimum execution time: 163_704_000 picoseconds.
		Weight::from_parts(151_754_295, 63886)
			// Standard Error: 1_029
			.saturating_add(Weight::from_parts(98_091, 0).saturating_mul(u.into()))
			// Standard Error: 10_488
			.saturating_add(Weight::from_parts(224_756, 0).saturating_mul(e.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `EthereumEvents::NftT1Contracts` (r:0 w:1)
	/// Proof: `EthereumEvents::NftT1Contracts` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn set_nft_contract_map_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_051_000 picoseconds.
		Weight::from_parts(7_280_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::UncheckedEvents` (r:1 w:1)
	/// Proof: `EthereumEvents::UncheckedEvents` (`max_values`: Some(1), `max_size`: Some(38002), added: 38497, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::EventChallengePeriod` (r:1 w:0)
	/// Proof: `EthereumEvents::EventChallengePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::QuorumFactor` (r:1 w:0)
	/// Proof: `EthereumEvents::QuorumFactor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::EventsPendingChallenge` (r:1 w:1)
	/// Proof: `EthereumEvents::EventsPendingChallenge` (`max_values`: Some(1), `max_size`: Some(62401), added: 62896, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[1, 10]`.
	/// The range of component `u` is `[1, 499]`.
	fn submit_checkevent_result(_v: u32, u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `391 + u * (76 ±0) + v * (64 ±0)`
		//  Estimated: `63886`
		// Minimum execution time: 41_531_000 picoseconds.
		Weight::from_parts(42_073_207, 63886)
			// Standard Error: 2_457
			.saturating_add(Weight::from_parts(512_288, 0).saturating_mul(u.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::EventsPendingChallenge` (r:1 w:1)
	/// Proof: `EthereumEvents::EventsPendingChallenge` (`max_values`: Some(1), `max_size`: Some(62401), added: 62896, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::QuorumFactor` (r:1 w:0)
	/// Proof: `EthereumEvents::QuorumFactor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::Challenges` (r:1 w:0)
	/// Proof: `EthereumEvents::Challenges` (`max_values`: None, `max_size`: Some(1681), added: 4156, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ProcessedEthereumEvents` (r:1 w:0)
	/// Proof: `EthBridge::ProcessedEthereumEvents` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Session::Validators` (r:1 w:0)
	/// Proof: `Session::Validators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::Reports` (r:1 w:1)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:1 w:1)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[1, 10]`.
	/// The range of component `e` is `[1, 49]`.
	fn process_event_with_successful_challenge(v: u32, e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1144 + e * (122 ±0) + v * (74 ±0)`
		//  Estimated: `63886 + e * (122 ±0) + v * (75 ±0)`
		// Minimum execution time: 117_273_000 picoseconds.
		Weight::from_parts(117_615_544, 63886)
			// Standard Error: 26_620
			.saturating_add(Weight::from_parts(72_697, 0).saturating_mul(v.into()))
			// Standard Error: 5_205
			.saturating_add(Weight::from_parts(1_049_331, 0).saturating_mul(e.into()))
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 122).saturating_mul(e.into()))
			.saturating_add(Weight::from_parts(0, 75).saturating_mul(v.into()))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::EventsPendingChallenge` (r:1 w:1)
	/// Proof: `EthereumEvents::EventsPendingChallenge` (`max_values`: Some(1), `max_size`: Some(62401), added: 62896, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::QuorumFactor` (r:1 w:0)
	/// Proof: `EthereumEvents::QuorumFactor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::Challenges` (r:1 w:1)
	/// Proof: `EthereumEvents::Challenges` (`max_values`: None, `max_size`: Some(1681), added: 4156, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ProcessedEthereumEvents` (r:1 w:1)
	/// Proof: `EthBridge::ProcessedEthereumEvents` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Session::Validators` (r:1 w:0)
	/// Proof: `Session::Validators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::Reports` (r:1 w:1)
	/// Proof: `Offences::Reports` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Offences::ConcurrentReportsIndex` (r:1 w:1)
	/// Proof: `Offences::ConcurrentReportsIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AvnOffenceHandler::ReportedOffenders` (r:1 w:1)
	/// Proof: `AvnOffenceHandler::ReportedOffenders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AvnOffenceHandler::SlashingEnabled` (r:1 w:0)
	/// Proof: `AvnOffenceHandler::SlashingEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[1, 10]`.
	/// The range of component `e` is `[1, 49]`.
	fn process_event_without_successful_challenge(v: u32, e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1155 + e * (122 ±0) + v * (64 ±0)`
		//  Estimated: `63886 + e * (122 ±0) + v * (64 ±0)`
		// Minimum execution time: 123_203_000 picoseconds.
		Weight::from_parts(123_113_850, 63886)
			// Standard Error: 31_428
			.saturating_add(Weight::from_parts(138_834, 0).saturating_mul(v.into()))
			// Standard Error: 6_145
			.saturating_add(Weight::from_parts(1_065_221, 0).saturating_mul(e.into()))
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(Weight::from_parts(0, 122).saturating_mul(e.into()))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(v.into()))
	}
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::EventsPendingChallenge` (r:1 w:0)
	/// Proof: `EthereumEvents::EventsPendingChallenge` (`max_values`: Some(1), `max_size`: Some(62401), added: 62896, mode: `MaxEncodedLen`)
	/// Storage: `EthereumEvents::Challenges` (r:1 w:1)
	/// Proof: `EthereumEvents::Challenges` (`max_values`: None, `max_size`: Some(1681), added: 4156, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[3, 10]`.
	/// The range of component `e` is `[1, 49]`.
	/// The range of component `c` is `[1, 49]`.
	fn challenge_event(v: u32, e: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `551 + c * (32 ±0) + e * (122 ±0) + v * (64 ±0)`
		//  Estimated: `63886`
		// Minimum execution time: 47_321_000 picoseconds.
		Weight::from_parts(46_092_838, 63886)
			// Standard Error: 11_322
			.saturating_add(Weight::from_parts(62_677, 0).saturating_mul(v.into()))
			// Standard Error: 1_740
			.saturating_add(Weight::from_parts(255_671, 0).saturating_mul(e.into()))
			// Standard Error: 1_740
			.saturating_add(Weight::from_parts(31_400, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `EthereumEvents::EventChallengePeriod` (r:0 w:1)
	/// Proof: `EthereumEvents::EventChallengePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_event_challenge_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_440_000 picoseconds.
		Weight::from_parts(9_640_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}