//! Autogenerated weights for pallet_token_manager
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-04-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-1-153`, CPU: `AMD EPYC 7R32`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./avn-parachain-collator
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// frame-weight-template.hbs
// --pallet
// pallet_token_manager
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// token_manager_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_token_manager.
pub trait WeightInfo {
	fn proxy_with_non_avt_token() -> Weight;
	fn signed_transfer() -> Weight;
	fn transfer_non_avt() -> Weight;
	fn transfer_native() -> Weight;
	fn schedule_direct_lower() -> Weight;
	fn execute_avt_lower() -> Weight;
	fn execute_non_avt_lower() -> Weight;
	fn schedule_signed_lower() -> Weight;
	fn transfer_from_treasury() -> Weight;
	fn regenerate_lower_proof() -> Weight;
	fn set_lower_schedule_period() -> Weight;
	fn toggle_lowering() -> Weight;
	fn set_native_token_eth_address() -> Weight;
}

/// Weights for pallet_token_manager using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TokenManager::Nonces` (r:1 w:1)
	/// Proof: `TokenManager::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Balances` (r:2 w:2)
	/// Proof: `TokenManager::Balances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn proxy_with_non_avt_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `850`
		//  Estimated: `6108`
		// Minimum execution time: 172_464_000 picoseconds.
		Weight::from_parts(173_374_000, 6108)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::Nonces` (r:1 w:1)
	/// Proof: `TokenManager::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Balances` (r:2 w:2)
	/// Proof: `TokenManager::Balances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn signed_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `850`
		//  Estimated: `6108`
		// Minimum execution time: 159_394_000 picoseconds.
		Weight::from_parts(161_163_000, 6108)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Balances` (r:2 w:2)
	/// Proof: `TokenManager::Balances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn transfer_non_avt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `806`
		//  Estimated: `6108`
		// Minimum execution time: 48_351_000 picoseconds.
		Weight::from_parts(49_201_000, 6108)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn transfer_native() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `333`
		//  Estimated: `6196`
		// Minimum execution time: 89_182_000 picoseconds.
		Weight::from_parts(90_193_000, 6196)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerAccountId` (r:1 w:0)
	/// Proof: `TokenManager::LowerAccountId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerNonce` (r:1 w:1)
	/// Proof: `TokenManager::LowerNonce` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerSchedulePeriod` (r:1 w:0)
	/// Proof: `TokenManager::LowerSchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(38963), added: 41438, mode: `MaxEncodedLen`)
	fn schedule_direct_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `42428`
		// Minimum execution time: 43_121_000 picoseconds.
		Weight::from_parts(43_881_000, 42428)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::Instance` (r:1 w:0)
	/// Proof: `EthBridge::Instance` (`max_values`: Some(1), `max_size`: Some(578), added: 1073, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowersPendingProof` (r:0 w:1)
	/// Proof: `TokenManager::LowersPendingProof` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	fn execute_avt_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `742`
		//  Estimated: `22431`
		// Minimum execution time: 97_732_000 picoseconds.
		Weight::from_parts(99_132_000, 22431)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Balances` (r:1 w:1)
	/// Proof: `TokenManager::Balances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::Instance` (r:1 w:0)
	/// Proof: `EthBridge::Instance` (`max_values`: Some(1), `max_size`: Some(578), added: 1073, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowersPendingProof` (r:0 w:1)
	/// Proof: `TokenManager::LowersPendingProof` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	fn execute_non_avt_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `982`
		//  Estimated: `22431`
		// Minimum execution time: 79_061_000 picoseconds.
		Weight::from_parts(80_162_000, 22431)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Nonces` (r:1 w:1)
	/// Proof: `TokenManager::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerAccountId` (r:1 w:0)
	/// Proof: `TokenManager::LowerAccountId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerNonce` (r:1 w:1)
	/// Proof: `TokenManager::LowerNonce` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerSchedulePeriod` (r:1 w:0)
	/// Proof: `TokenManager::LowerSchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(38963), added: 41438, mode: `MaxEncodedLen`)
	fn schedule_signed_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `439`
		//  Estimated: `42428`
		// Minimum execution time: 157_584_000 picoseconds.
		Weight::from_parts(158_664_000, 42428)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn transfer_from_treasury() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `226`
		//  Estimated: `6196`
		// Minimum execution time: 78_662_000 picoseconds.
		Weight::from_parts(79_752_000, 6196)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowersReadyToClaim` (r:1 w:1)
	/// Proof: `TokenManager::LowersReadyToClaim` (`max_values`: None, `max_size`: Some(10138), added: 12613, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::Instance` (r:1 w:0)
	/// Proof: `EthBridge::Instance` (`max_values`: Some(1), `max_size`: Some(578), added: 1073, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowersPendingProof` (r:0 w:1)
	/// Proof: `TokenManager::LowersPendingProof` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	fn regenerate_lower_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `505`
		//  Estimated: `22431`
		// Minimum execution time: 54_071_000 picoseconds.
		Weight::from_parts(54_761_000, 22431)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowerSchedulePeriod` (r:0 w:1)
	/// Proof: `TokenManager::LowerSchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_lower_schedule_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_750_000 picoseconds.
		Weight::from_parts(10_081_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:0 w:1)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn toggle_lowering() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_111_000 picoseconds.
		Weight::from_parts(10_340_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:1)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn set_native_token_eth_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `138`
		//  Estimated: `1505`
		// Minimum execution time: 16_910_000 picoseconds.
		Weight::from_parts(17_391_000, 1505)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `TokenManager::Nonces` (r:1 w:1)
	/// Proof: `TokenManager::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Balances` (r:2 w:2)
	/// Proof: `TokenManager::Balances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn proxy_with_non_avt_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `850`
		//  Estimated: `6108`
		// Minimum execution time: 172_464_000 picoseconds.
		Weight::from_parts(173_374_000, 6108)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::Nonces` (r:1 w:1)
	/// Proof: `TokenManager::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Balances` (r:2 w:2)
	/// Proof: `TokenManager::Balances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn signed_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `850`
		//  Estimated: `6108`
		// Minimum execution time: 159_394_000 picoseconds.
		Weight::from_parts(161_163_000, 6108)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Balances` (r:2 w:2)
	/// Proof: `TokenManager::Balances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn transfer_non_avt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `806`
		//  Estimated: `6108`
		// Minimum execution time: 48_351_000 picoseconds.
		Weight::from_parts(49_201_000, 6108)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn transfer_native() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `333`
		//  Estimated: `6196`
		// Minimum execution time: 89_182_000 picoseconds.
		Weight::from_parts(90_193_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerAccountId` (r:1 w:0)
	/// Proof: `TokenManager::LowerAccountId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerNonce` (r:1 w:1)
	/// Proof: `TokenManager::LowerNonce` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerSchedulePeriod` (r:1 w:0)
	/// Proof: `TokenManager::LowerSchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(38963), added: 41438, mode: `MaxEncodedLen`)
	fn schedule_direct_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `42428`
		// Minimum execution time: 43_121_000 picoseconds.
		Weight::from_parts(43_881_000, 42428)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::Instance` (r:1 w:0)
	/// Proof: `EthBridge::Instance` (`max_values`: Some(1), `max_size`: Some(578), added: 1073, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowersPendingProof` (r:0 w:1)
	/// Proof: `TokenManager::LowersPendingProof` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	fn execute_avt_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `742`
		//  Estimated: `22431`
		// Minimum execution time: 97_732_000 picoseconds.
		Weight::from_parts(99_132_000, 22431)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Balances` (r:1 w:1)
	/// Proof: `TokenManager::Balances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::Instance` (r:1 w:0)
	/// Proof: `EthBridge::Instance` (`max_values`: Some(1), `max_size`: Some(578), added: 1073, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowersPendingProof` (r:0 w:1)
	/// Proof: `TokenManager::LowersPendingProof` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	fn execute_non_avt_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `982`
		//  Estimated: `22431`
		// Minimum execution time: 79_061_000 picoseconds.
		Weight::from_parts(80_162_000, 22431)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Nonces` (r:1 w:1)
	/// Proof: `TokenManager::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerAccountId` (r:1 w:0)
	/// Proof: `TokenManager::LowerAccountId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerNonce` (r:1 w:1)
	/// Proof: `TokenManager::LowerNonce` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerSchedulePeriod` (r:1 w:0)
	/// Proof: `TokenManager::LowerSchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(38963), added: 41438, mode: `MaxEncodedLen`)
	fn schedule_signed_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `439`
		//  Estimated: `42428`
		// Minimum execution time: 157_584_000 picoseconds.
		Weight::from_parts(158_664_000, 42428)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn transfer_from_treasury() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `226`
		//  Estimated: `6196`
		// Minimum execution time: 78_662_000 picoseconds.
		Weight::from_parts(79_752_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowersReadyToClaim` (r:1 w:1)
	/// Proof: `TokenManager::LowersReadyToClaim` (`max_values`: None, `max_size`: Some(10138), added: 12613, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20946), added: 21441, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::Instance` (r:1 w:0)
	/// Proof: `EthBridge::Instance` (`max_values`: Some(1), `max_size`: Some(578), added: 1073, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowersPendingProof` (r:0 w:1)
	/// Proof: `TokenManager::LowersPendingProof` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	fn regenerate_lower_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `505`
		//  Estimated: `22431`
		// Minimum execution time: 54_071_000 picoseconds.
		Weight::from_parts(54_761_000, 22431)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowerSchedulePeriod` (r:0 w:1)
	/// Proof: `TokenManager::LowerSchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_lower_schedule_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_750_000 picoseconds.
		Weight::from_parts(10_081_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:0 w:1)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn toggle_lowering() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_111_000 picoseconds.
		Weight::from_parts(10_340_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:1)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn set_native_token_eth_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `138`
		//  Estimated: `1505`
		// Minimum execution time: 16_910_000 picoseconds.
		Weight::from_parts(17_391_000, 1505)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}