
//! Autogenerated weights for pallet_cross_chain_voting
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-03-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Linux-Spacelord`, CPU: `AMD Ryzen 7 2700X Eight-Core Processor`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/avn-parachain-collator
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// .maintain/frame-weight-template.hbs
// --pallet
// pallet_cross_chain_voting
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// cross_chain_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_cross_chain_voting.
pub trait WeightInfo {
	fn link_account() -> Weight;
	fn unlink_account() -> Weight;
}

/// Weights for pallet_cross_chain_voting using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `CrossChainVoting::LinkedAccountToIdentity` (r:1 w:1)
	/// Proof: `CrossChainVoting::LinkedAccountToIdentity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `CrossChainVoting::LinkedAccounts` (r:1 w:1)
	/// Proof: `CrossChainVoting::LinkedAccounts` (`max_values`: None, `max_size`: Some(357), added: 2832, mode: `MaxEncodedLen`)
	fn link_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3822`
		// Minimum execution time: 75_722_000 picoseconds.
		Weight::from_parts(76_754_000, 3822)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `CrossChainVoting::LinkedAccountToIdentity` (r:1 w:1)
	/// Proof: `CrossChainVoting::LinkedAccountToIdentity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `CrossChainVoting::LinkedAccounts` (r:1 w:1)
	/// Proof: `CrossChainVoting::LinkedAccounts` (`max_values`: None, `max_size`: Some(357), added: 2832, mode: `MaxEncodedLen`)
	fn unlink_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `3822`
		// Minimum execution time: 27_011_000 picoseconds.
		Weight::from_parts(27_532_000, 3822)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `CrossChainVoting::LinkedAccountToIdentity` (r:1 w:1)
	/// Proof: `CrossChainVoting::LinkedAccountToIdentity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `CrossChainVoting::LinkedAccounts` (r:1 w:1)
	/// Proof: `CrossChainVoting::LinkedAccounts` (`max_values`: None, `max_size`: Some(357), added: 2832, mode: `MaxEncodedLen`)
	fn link_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3822`
		// Minimum execution time: 75_722_000 picoseconds.
		Weight::from_parts(76_754_000, 3822)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `CrossChainVoting::LinkedAccountToIdentity` (r:1 w:1)
	/// Proof: `CrossChainVoting::LinkedAccountToIdentity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `CrossChainVoting::LinkedAccounts` (r:1 w:1)
	/// Proof: `CrossChainVoting::LinkedAccounts` (`max_values`: None, `max_size`: Some(357), added: 2832, mode: `MaxEncodedLen`)
	fn unlink_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `3822`
		// Minimum execution time: 27_011_000 picoseconds.
		Weight::from_parts(27_532_000, 3822)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}