
//! Autogenerated weights for pallet_avn_anchor
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-03-23, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-2-182`, CPU: `AMD EPYC 7R32`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./avn-parachain-collator
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// frame-weight-template.hbs
// --pallet
// pallet_avn_anchor
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// avn_anchor_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_avn_anchor.
pub trait WeightInfo {
	fn register_chain_handler() -> Weight;
	fn update_chain_handler() -> Weight;
	fn submit_checkpoint_with_identity() -> Weight;
	fn signed_register_chain_handler() -> Weight;
	fn signed_update_chain_handler() -> Weight;
	fn signed_submit_checkpoint_with_identity() -> Weight;
	fn register_appchain() -> Weight;
	fn set_checkpoint_fee() -> Weight;
}

/// Weights for pallet_avn_anchor using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn register_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_147_000 picoseconds.
		Weight::from_parts(3_355_000, 0)
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:2 w:2)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn update_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `6044`
		// Minimum execution time: 19_250_000 picoseconds.
		Weight::from_parts(29_189_000, 6044)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::OriginIdToCheckpoint` (r:1 w:1)
	/// Proof: `AvnAnchor::OriginIdToCheckpoint` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextCheckpointId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextCheckpointId` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::CheckpointFee` (r:1 w:0)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Checkpoints` (r:0 w:1)
	/// Proof: `AvnAnchor::Checkpoints` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn submit_checkpoint_with_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `699`
		//  Estimated: `6196`
		// Minimum execution time: 82_793_000 picoseconds.
		Weight::from_parts(96_369_000, 6196)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	fn signed_register_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_578_000 picoseconds.
		Weight::from_parts(4_356_000, 0)
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:2 w:2)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn signed_update_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `155`
		//  Estimated: `6044`
		// Minimum execution time: 113_614_000 picoseconds.
		Weight::from_parts(142_348_000, 6044)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::OriginIdToCheckpoint` (r:1 w:1)
	/// Proof: `AvnAnchor::OriginIdToCheckpoint` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextCheckpointId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextCheckpointId` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::CheckpointFee` (r:1 w:0)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Checkpoints` (r:0 w:1)
	/// Proof: `AvnAnchor::Checkpoints` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn signed_submit_checkpoint_with_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `614`
		//  Estimated: `6196`
		// Minimum execution time: 176_816_000 picoseconds.
		Weight::from_parts(238_275_000, 6196)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:1)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:1)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextChainId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextChainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:1 w:1)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::RegisteredAppchains` (r:1 w:1)
	/// Proof: `AvnAnchor::RegisteredAppchains` (`max_values`: Some(1), `max_size`: Some(502), added: 997, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::AssetIdToChainId` (r:0 w:1)
	/// Proof: `AvnAnchor::AssetIdToChainId` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn register_appchain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `6163`
		// Minimum execution time: 34_626_000 picoseconds.
		Weight::from_parts(36_051_000, 6163)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `AvnAnchor::CheckpointFee` (r:0 w:1)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn set_checkpoint_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_400_000 picoseconds.
		Weight::from_parts(9_740_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn register_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_147_000 picoseconds.
		Weight::from_parts(3_355_000, 0)
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:2 w:2)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn update_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `327`
		//  Estimated: `6044`
		// Minimum execution time: 28_840_000 picoseconds.
		Weight::from_parts(29_511_000, 6044)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::OriginIdToCheckpoint` (r:1 w:1)
	/// Proof: `AvnAnchor::OriginIdToCheckpoint` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextCheckpointId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextCheckpointId` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::CheckpointFee` (r:1 w:0)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Checkpoints` (r:0 w:1)
	/// Proof: `AvnAnchor::Checkpoints` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn submit_checkpoint_with_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `648`
		//  Estimated: `6196`
		// Minimum execution time: 95_332_000 picoseconds.
		Weight::from_parts(95_942_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	fn signed_register_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_578_000 picoseconds.
		Weight::from_parts(4_356_000, 0)
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:2 w:2)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn signed_update_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `343`
		//  Estimated: `6044`
		// Minimum execution time: 173_704_000 picoseconds.
		Weight::from_parts(175_424_000, 6044)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::OriginIdToCheckpoint` (r:1 w:1)
	/// Proof: `AvnAnchor::OriginIdToCheckpoint` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextCheckpointId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextCheckpointId` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::CheckpointFee` (r:1 w:0)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Checkpoints` (r:0 w:1)
	/// Proof: `AvnAnchor::Checkpoints` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn signed_submit_checkpoint_with_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `614`
		//  Estimated: `6196`
		// Minimum execution time: 176_816_000 picoseconds.
		Weight::from_parts(238_275_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:1)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:1)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextChainId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextChainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:1 w:1)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::RegisteredAppchains` (r:1 w:1)
	/// Proof: `AvnAnchor::RegisteredAppchains` (`max_values`: Some(1), `max_size`: Some(502), added: 997, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::AssetIdToChainId` (r:0 w:1)
	/// Proof: `AvnAnchor::AssetIdToChainId` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn register_appchain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `6163`
		// Minimum execution time: 34_626_000 picoseconds.
		Weight::from_parts(36_051_000, 6163)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `AvnAnchor::CheckpointFee` (r:0 w:1)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn set_checkpoint_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_386_000 picoseconds.
		Weight::from_parts(8_852_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}