
//! Autogenerated weights for pallet_watchtower
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2025-10-29, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-16-102`, CPU: `Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/tnf-node
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// .maintain/frame-weight-template.hbs
// --pallet
// pallet_watchtower
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// WT-weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_watchtower.
pub trait WeightInfo {
	fn submit_external_proposal() -> Weight;
	fn signed_submit_external_proposal() -> Weight;
	fn vote() -> Weight;
	fn vote_end_proposal() -> Weight;
	fn signed_vote() -> Weight;
	fn signed_vote_end_proposal() -> Weight;
	fn unsigned_vote() -> Weight;
	fn unsigned_vote_end_proposal() -> Weight;
	fn finalise_proposal() -> Weight;
	fn set_admin_config_voting() -> Weight;
	fn set_admin_config_account() -> Weight;
	fn active_proposal_expiry_status() -> Weight;
	fn finalise_expired_voting() -> Weight;
}

/// Weights for pallet_watchtower using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Watchtower::AdminAccount` (r:1 w:0)
	/// Proof: `Watchtower::AdminAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::MinVotingPeriod` (r:1 w:0)
	/// Proof: `Watchtower::MinVotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ExternalRef` (r:1 w:1)
	/// Proof: `Watchtower::ExternalRef` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn submit_external_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `8196`
		// Minimum execution time: 25_726_000 picoseconds.
		Weight::from_parts(27_724_000, 8196)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Watchtower::AdminAccount` (r:1 w:0)
	/// Proof: `Watchtower::AdminAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::MinVotingPeriod` (r:1 w:0)
	/// Proof: `Watchtower::MinVotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ExternalRef` (r:1 w:1)
	/// Proof: `Watchtower::ExternalRef` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn signed_submit_external_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `8196`
		// Minimum execution time: 28_007_000 picoseconds.
		Weight::from_parts(36_989_000, 8196)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:0)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `266`
		//  Estimated: `8196`
		// Minimum execution time: 29_508_000 picoseconds.
		Weight::from_parts(36_665_000, 8196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `AnchorSummary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `AnchorSummary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:0)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn vote_end_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `646`
		//  Estimated: `8196`
		// Minimum execution time: 52_275_000 picoseconds.
		Weight::from_parts(61_505_000, 8196)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:0)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn signed_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `266`
		//  Estimated: `8196`
		// Minimum execution time: 114_240_000 picoseconds.
		Weight::from_parts(146_835_000, 8196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `AnchorSummary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `AnchorSummary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:0)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn signed_vote_end_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `646`
		//  Estimated: `8196`
		// Minimum execution time: 144_130_000 picoseconds.
		Weight::from_parts(177_289_000, 8196)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:0)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn unsigned_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `266`
		//  Estimated: `8196`
		// Minimum execution time: 78_406_000 picoseconds.
		Weight::from_parts(92_863_000, 8196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `AnchorSummary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `AnchorSummary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:0)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn unsigned_vote_end_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `646`
		//  Estimated: `8196`
		// Minimum execution time: 104_756_000 picoseconds.
		Weight::from_parts(124_459_000, 8196)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:2 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:2)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `AnchorSummary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `AnchorSummary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:1)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::InternalProposalQueue` (r:1 w:1)
	/// Proof: `Watchtower::InternalProposalQueue` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:0 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn finalise_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `535`
		//  Estimated: `15402`
		// Minimum execution time: 56_663_000 picoseconds.
		Weight::from_parts(93_432_000, 15402)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `Watchtower::MinVotingPeriod` (r:1 w:1)
	/// Proof: `Watchtower::MinVotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `1489`
		// Minimum execution time: 10_814_000 picoseconds.
		Weight::from_parts(11_685_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Watchtower::AdminAccount` (r:1 w:1)
	/// Proof: `Watchtower::AdminAccount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `1489`
		// Minimum execution time: 10_814_000 picoseconds.
		Weight::from_parts(11_685_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	fn active_proposal_expiry_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `222`
		//  Estimated: `8196`
		// Minimum execution time: 7_659_000 picoseconds.
		Weight::from_parts(8_159_000, 8196)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `AnchorSummary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `AnchorSummary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:1)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::InternalProposalQueue` (r:1 w:1)
	/// Proof: `Watchtower::InternalProposalQueue` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:2)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:0 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn finalise_expired_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `340`
		//  Estimated: `8196`
		// Minimum execution time: 38_859_000 picoseconds.
		Weight::from_parts(41_183_000, 8196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Watchtower::AdminAccount` (r:1 w:0)
	/// Proof: `Watchtower::AdminAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::MinVotingPeriod` (r:1 w:0)
	/// Proof: `Watchtower::MinVotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ExternalRef` (r:1 w:1)
	/// Proof: `Watchtower::ExternalRef` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn submit_external_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `8196`
		// Minimum execution time: 25_726_000 picoseconds.
		Weight::from_parts(27_724_000, 8196)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Watchtower::AdminAccount` (r:1 w:0)
	/// Proof: `Watchtower::AdminAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::MinVotingPeriod` (r:1 w:0)
	/// Proof: `Watchtower::MinVotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ExternalRef` (r:1 w:1)
	/// Proof: `Watchtower::ExternalRef` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn signed_submit_external_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `8196`
		// Minimum execution time: 28_007_000 picoseconds.
		Weight::from_parts(36_989_000, 8196)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:0)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `266`
		//  Estimated: `8196`
		// Minimum execution time: 29_508_000 picoseconds.
		Weight::from_parts(36_665_000, 8196)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `AnchorSummary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `AnchorSummary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:0)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn vote_end_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `646`
		//  Estimated: `8196`
		// Minimum execution time: 52_275_000 picoseconds.
		Weight::from_parts(61_505_000, 8196)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:0)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn signed_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `266`
		//  Estimated: `8196`
		// Minimum execution time: 114_240_000 picoseconds.
		Weight::from_parts(146_835_000, 8196)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `AnchorSummary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `AnchorSummary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:0)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn signed_vote_end_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `646`
		//  Estimated: `8196`
		// Minimum execution time: 144_130_000 picoseconds.
		Weight::from_parts(177_289_000, 8196)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:0)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn unsigned_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `266`
		//  Estimated: `8196`
		// Minimum execution time: 78_406_000 picoseconds.
		Weight::from_parts(92_863_000, 8196)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `AnchorSummary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `AnchorSummary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:0)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn unsigned_vote_end_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `646`
		//  Estimated: `8196`
		// Minimum execution time: 104_756_000 picoseconds.
		Weight::from_parts(124_459_000, 8196)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:2 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:2)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `AnchorSummary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `AnchorSummary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:1)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::InternalProposalQueue` (r:1 w:1)
	/// Proof: `Watchtower::InternalProposalQueue` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:0 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn finalise_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `535`
		//  Estimated: `15402`
		// Minimum execution time: 56_663_000 picoseconds.
		Weight::from_parts(93_432_000, 15402)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `Watchtower::MinVotingPeriod` (r:1 w:1)
	/// Proof: `Watchtower::MinVotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `1489`
		// Minimum execution time: 10_814_000 picoseconds.
		Weight::from_parts(11_685_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Watchtower::AdminAccount` (r:1 w:1)
	/// Proof: `Watchtower::AdminAccount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `1489`
		// Minimum execution time: 10_814_000 picoseconds.
		Weight::from_parts(11_685_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	fn active_proposal_expiry_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `222`
		//  Estimated: `8196`
		// Minimum execution time: 7_659_000 picoseconds.
		Weight::from_parts(8_159_000, 8196)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `AnchorSummary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `AnchorSummary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:1)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::InternalProposalQueue` (r:1 w:1)
	/// Proof: `Watchtower::InternalProposalQueue` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(4731), added: 7206, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:2)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:0 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn finalise_expired_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `340`
		//  Estimated: `8196`
		// Minimum execution time: 38_859_000 picoseconds.
		Weight::from_parts(41_183_000, 8196)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
}